const {expect} = require('chai')
const request = require('supertest')
const db = require('../db')
const app = require('../index')
const Comments = db.model('comments')
const Post = db.model('post')
const assert = require('assert')
const User = db.model('user')
const agent = require('supertest')(app)

