const Users = [
    {firstName: 'Dan', lastName: 'Gutt', email: 'dgutt@email.com', password: '12345', userType: 'user'},
    {firstName: 'Shaheed', lastName: 'Shamsi', email: 'sshamsi@email.com', password: '12345', userType: 'user'},
    {firstName: 'Minh', lastName: 'Ngyuen', email: 'mngyuen@email.com', password: '12345', userType: 'user'},
    {firstName: 'Chris', lastName: 'Jones', email: 'cjones@email.com', password: '12345', userType: 'user'},
]
const Posts = [
    {latitude: 41.89671271, longitude: -87.63702022, mediaType: "video", title: "Chicago Marathon", text: "Using a variety of traps, Bunny first dispatches of Rinky and Gimera. Next, Frank, who is unaware of the other two's fate, is seen taking off from a ", mediaLink: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4", categoryId: 1},
    {latitude: 41.89536942, longitude: -87.63687061, mediaType: "image", title: "Beer Fest", text: "German beer festival", mediaLink: "https://cdn.muenchen-p.de/.imaging/stk/responsive/galleryPreview980/dms/wiesn/2017/exithamster/exithamster/zelte-hp/document/zelte-hp.jpg", categoryId: 3},
    {latitude: 41.89470126, longitude: -87.63738955, mediaType: "image", title: "Tomato fest", text: "Little Italia tomato festival", mediaLink: "https://i.pinimg.com/originals/fd/12/d0/fd12d09762450b7cceb5954bf9b6b3c5.jpg", categoryId: 3},
    {latitude: 41.89580093, longitude: -87.63959151, mediaType: "image", title: "Cuban Cigar", text: "Little Havana Cuban fest", mediaLink: "https://i.amz.mshcdn.com/H4IUTO_uOWyGJ4rwztY2deJU2LM=/fit-in/1200x9600/http%3A%2F%2Fmashable.com%2Fwp-content%2Fuploads%2F2014%2F05%2Fbbblow.gif", categoryId: 2},
    {latitude: 41.89370126, longitude: -87.63737755, mediaType: "image", title: "Bike Race", text: "Bicycle racing", mediaLink: "https://i.imgur.com/rskdPAy.gif", categoryId: 2},
    {latitude: 41.89562154, longitude: -87.63920034, mediaType: "image", title: "Sox Suck", text: "The Sox and the Cardinals suck!", mediaLink: "http://madison365.com/wp-content/uploads/2016/10/Chicago_Cubs.jpg", categoryId: 1},
]

const Categories = [
    {title: 'News'},
    {title: 'Commercial'},
    {title: 'Entertainment'},
]

const CommentsData = [
    {content: "This app is great!", userId: 1, postId: 1},
    {content: "Buckbunny is a transformational film!!", userId: 2, postId: 1},
    {content: "Best movie of the year!", userId: 3, postId: 1},
    {content: "A truly profound take on the bunny genre", userId: 4, postId: 1},
    {content: "This app is great!", userId: 1, postId: 1},
    {content: "Buckbunny is a transformational film!!", userId: 2, postId: 1},
    {content: "Best movie of the year!", userId: 3, postId: 1},
    {content: "A truly profound take on the bunny genre", userId: 4, postId: 1},
    {content: "This app is great!", userId: 1, postId: 1},
    {content: "Buckbunny is a transformational film!!", userId: 2, postId: 1},
    {content: "Best movie of the year!", userId: 3, postId: 1},
    {content: "A truly profound take on the bunny genre", userId: 4, postId: 1},
    {content: "This app is great!", userId: 1, postId: 1},
    {content: "Buckbunny is a transformational film!!", userId: 2, postId: 1},
    {content: "Best movie of the year!", userId: 3, postId: 1},
    {content: "A truly profound take on the bunny genre", userId: 4, postId: 1},
    {content: "This app is great!", userId: 1, postId: 1},
    {content: "Buckbunny is a transformational film!!", userId: 2, postId: 1},
    {content: "Best movie of the year!", userId: 3, postId: 1},
    {content: "A truly profound take on the bunny genre", userId: 4, postId: 1},
    {content: "The beer here is so good!", userId: 1, postId: 2},
    {content: "I can't wait to try the sauerkraut", userId: 2, postId: 2},
    {content: "Best party of the year!!", userId: 3, postId: 2},
    {content: "A truly profound take on beer", userId: 4, postId: 2},
    {content: "The beer here is so good!", userId: 1, postId: 2},
    {content: "I can't wait to try the sauerkraut", userId: 2, postId: 2},
    {content: "Best party of the year!!", userId: 3, postId: 2},
    {content: "A truly profound take on beer", userId: 4, postId: 2},
    {content: "The beer here is so good!", userId: 1, postId: 2},
    {content: "I can't wait to try the sauerkraut", userId: 2, postId: 2},
    {content: "Best party of the year!!", userId: 3, postId: 2},
    {content: "A truly profound take on beer", userId: 4, postId: 2},
    {content: "The beer here is so good!", userId: 1, postId: 2},
    {content: "I can't wait to try the sauerkraut", userId: 2, postId: 2},
    {content: "Best party of the year!!", userId: 3, postId: 2},
    {content: "A truly profound take on beer", userId: 4, postId: 2},
    {content: "The beer here is so good!", userId: 1, postId: 2},
    {content: "I can't wait to try the sauerkraut", userId: 2, postId: 2},
    {content: "Best party of the year!!", userId: 3, postId: 2},
    {content: "A truly profound take on beer", userId: 4, postId: 2},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 3},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 4},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 5},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 1, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 2, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 3, postId: 6},
    {content: "lorem ipsum dolor sit amet", userId: 4, postId: 6},
]




module.exports = {Posts, Categories, CommentsData, Users}